# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - 5.5
    - 5.4
    - 5.3

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.5.1  WP_MULTISITE=0
    - WP_VERSION=3.5    WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.5.1  WP_MULTISITE=1

matrix:
  allow_failures:
      - env:
        - WP_VERSION=master WP_MULTISITE=0
        - WP_VERSION=master WP_MULTISITE=1

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq ffmpeg

# Grab the setup script and execute
before_script:
    - composer self-update
    - composer install --dev --no-interaction
    - wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
  - whoami
  - ls -l
